#!/bin/sh

# both monitors use the name/serial if connected via DP
MON_NAME="ViewSonic Corporation VX2758-Series VVF190100000"
MON_LEFT="DP-1"
MON_RIGHT="DP-2"
MON_COUNT=$(swaymsg -t get_outputs --pretty | grep "$MON_NAME" | wc --lines)
if [ "$MON_COUNT" -gt "1" ]; then
    swaymsg -- "output \"$MON_LEFT\" pos 0 0"
    swaymsg -- "output \"$MON_RIGHT\" pos 2560 0"

    swaymsg -- "workspace 1 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 2 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 3 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 4 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 5 output \"$MON_RIGHT\" \"$MON_LEFT\""

    swaymsg -- "workspace 6 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 7 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 8 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 9 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 10 output \"$MON_LEFT\" \"$MON_RIGHT\""

    # save focused and visible workspace
    FOCUSED=$(swaymsg -t get_workspaces | jq ".[] | select(.focused == true).num")
    VISIBLE=$(swaymsg -t get_workspaces | jq ".[] | select(.visible == true and .focused == false).num")

    # free up workspace 1 and 2 to make sure they are assigned to the expected output
    # then switch back to the focused and visible workspace in case this is a hot reload
    swaymsg -- "workspace 1 ; workspace 6 ; workspace 2 ; workspace 1 ; workspace $VISIBLE ; workspace $FOCUSED"
else
    echo "Did not recognize home environment (monitors $MON_LEFT and $MON_RIGHT with name $MON_NAME)"
    exit 1
fi
