#!/bin/sh

MON_LEFT="ViewSonic Corporation VX2758-Series VVF201800102"
MON_RIGHT="ViewSonic Corporation VX2758-Series VVF190100000"

if (swaymsg -t get_outputs --pretty | grep "$MON_LEFT") && (swaymsg -t get_outputs --pretty | grep "$MON_RIGHT"); then
    swaymsg -- "output \"$MON_LEFT\" pos 0 0"
    swaymsg -- "output \"$MON_RIGHT\" pos 2560 0"

    swaymsg -- "workspace 1 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 2 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 3 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 4 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 5 output \"$MON_RIGHT\" \"$MON_LEFT\""

    swaymsg -- "workspace 6 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 7 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 8 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 9 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 10 output \"$MON_LEFT\" \"$MON_RIGHT\""
else
    echo "Did not recognize home environment (monitors $MON1 and $MON2)"
    exit 1
fi
