#!/bin/sh

MON_LEFT="ViewSonic Corporation VX2758-Series VVF201800102"
MON_RIGHT="ViewSonic Corporation VX2758-Series VVF190100000"

if (swaymsg -t get_outputs --pretty | grep "$MON_LEFT") && (swaymsg -t get_outputs --pretty | grep "$MON_RIGHT"); then
    swaymsg -- "output \"$MON_LEFT\" pos 0 0"
    swaymsg -- "output \"$MON_RIGHT\" pos 2560 0"

    swaymsg -- "workspace 1 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 2 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 3 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 4 output \"$MON_RIGHT\" \"$MON_LEFT\""
    swaymsg -- "workspace 5 output \"$MON_RIGHT\" \"$MON_LEFT\""

    swaymsg -- "workspace 6 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 7 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 8 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 9 output \"$MON_LEFT\" \"$MON_RIGHT\""
    swaymsg -- "workspace 10 output \"$MON_LEFT\" \"$MON_RIGHT\""

    # save focused and visible workspace
    FOCUSED=$(swaymsg -t get_workspaces | jq ".[] | select(.focused == true).num")
    VISIBLE=$(swaymsg -t get_workspaces | jq ".[] | select(.visible == true and .focused == false).num")

    # free up workspace 1 and 2 to make sure they are assigned to the expected output
    # then switch back to the focused and visible workspace in case this is a hot reload
    swaymsg -- "workspace 1 ; workspace 6 ; workspace 2 ; workspace 1 ; workspace $VISIBLE ; workspace $FOCUSED"
else
    echo "Did not recognize home environment (monitors $MON1 and $MON2)"
    exit 1
fi
