#!/usr/bin/env bash
set -eu

XRANDR_ARGS=""

while IFS= read -r dev; do
  XRANDR_ARGS+=" --output $dev --off"
done < <(
  xrandr | jc --xrandr | jq -r '
    .screens[] | .devices[] |
    select(.is_connected == true and .device_name != "eDP") |
    .device_name
  '
)
XRANDR_CMD="xrandr $XRANDR_ARGS --output eDP --auto"
$XRANDR_CMD
