#!/usr/bin/env bash
set -eu

OPTIONS=("logout" "logoutAndReboot" "logoutAndShutdown")
if [ $# -ne 1 ] || [[ ! " ${OPTIONS[*]} " =~ " $1 " ]]; then
    echo "Usage: $0 {${OPTIONS[*]}}"
    exit 1
fi

# make sure the fakwin service is running so shutdown actually works
systemctl --user start fakwin.service
qdbus6 org.kde.Shutdown /Shutdown "org.kde.Shutdown.$1"
