#!/bin/zsh

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 <profile_name> resticprofile_args..."
  echo "Examples: $0 rest show"
  echo "          $0 local snapshots"
  echo "          $0 local mount /mnt/backup"
  echo "          $0 local schedule"
  echo "          $0 local unschedule"
  exit 1
fi

PROFILE_NAME="${1}"
shift

# always update resticprofile config and make sure they have the correct permissions
sudo zsh -c "cat /etc/resticprofile/shared/defaults.toml \
                 /etc/resticprofile/config.toml \
                 /etc/resticprofile/shared/template.toml \
              > /etc/resticprofile/profiles.toml ; \
             chmod 400 /etc/resticprofile/profiles.toml ; \
             chown root:root /etc/resticprofile/config.toml ; \
             chmod 600 /etc/resticprofile/config.toml"

# call resticprofile with the remaining args
sudo resticprofile --config /etc/resticprofile/profiles.toml --name "${PROFILE_NAME}" $@
