#!/bin/zsh

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 <profile_name> resticprofile_args..."
  echo "Examples: $0 rest show"
  echo "          $0 local snapshots"
  echo "          $0 local mount /mnt/backup"
  echo "          $0 local schedule"
  echo "          $0 local unschedule"
  exit 1
fi

PROFILE_NAME="${1}"
shift

# always update resticprofile config
sudo zsh -c "cat /etc/resticprofile/config.toml /etc/resticprofile/template.toml > /etc/resticprofile/profiles.toml"

# call resticprofile with the remaining args
sudo resticprofile --name "${PROFILE_NAME}" $@
