#!/bin/sh

# check if we failed
# https://www.freedesktop.org/software/systemd/man/systemd.exec.html
if [ "$SERVICE_RESULT" == "success" ] && [ "$EXIT_CODE" == "exited" ];
then
	exit 0
fi

root-notify-send "$@
exit code: ${EXIT_STATUS}"
