#!/bin/sh

# check if we failed
# https://www.freedesktop.org/software/systemd/man/systemd.exec.html
if [ "$SERVICE_RESULT" == "success" ] && [ "$EXIT_CODE" == "exited" ];
then
	exit 0
fi
# The following is not perfect but better than hardcoding the user display/completely

#Detect the name of the display in use
display=":$(ls /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"

#Detect the user using such display
user="$(loginctl list-sessions --no-legend | awk '{print $3}' | head -n 1)"

#Detect the id of the user
uid=$(id -u $user)

sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus notify-send "$@"
