#!/bin/zsh

## Usage:
##   export-env.sh ${PATH}
function export-env() {
  echo "export-env called on $1"
  read -r -d '' PYTHON_SCRIPT << EOM
import regex
import sys
r = regex.compile("([a-zA-Z_]+[a-zA-Z0-9_]*)=(.*)")

with open("$1", "r") as f:
  for line in f.readlines():
    # skip comments
    line = line.strip()
    if line.startswith("#") or not line:
      continue

    m = r.match(line)
    if not m:
      print("Could not match decl: ", line, file=sys.stderr)
      continue

    name = m.group(1)
    val = m.group(2)

    # strip quotes if they exist
    if len(val) > 2 and val[0] == '"' and val[-1] == '"':
      val = val[1:-1]

    print("{}={}".format(name, val))
EOM
  python -c "${PYTHON_SCRIPT}" | while read -r line ; do
    export "$line"
  done
}

