#!/usr/bin/env bash

XRANDR_OUTPUT=$(xrandr --prop | jc --xrandr)

# should always stay static
MONLAP="eDP"

MON_LEFT=$(jq -r '
    .screens[] | .devices[] |
    select(.is_connected == true and .props.EdidModel.serial_number == "VVF190100000") |
    .device_name
  ' <<< $XRANDR_OUTPUT
)
MON_RIGHT=$(jq -r '
    .screens[] | .devices[] |
    select(.is_connected == true and .props.EdidModel.serial_number == "VVF201800199") |
    .device_name
  ' <<< $XRANDR_OUTPUT
)

if [[ -n "$MON_LEFT" && -n "$MON_RIGHT" ]]; then
    echo "detected dual_home setup"
    xrandr --output "$MON_RIGHT" --auto --right-of "$MON_LEFT" --output "$MON_LEFT" --mode "2560x1440" --rate "59.95" --output "$MONLAP" --off

    # generate the workspaces config and reload i3 to apply it
    cat > /tmp/workspaces_generated.conf <<EOF
set \$MON1 $MON_LEFT
set \$MON2 $MON_RIGHT
set \$MONLAP eDP

workspace \$ws1 output \$MON2 \$MONLAP \$MON1
workspace \$ws2 output \$MON2 \$MONLAP \$MON1
workspace \$ws3 output \$MON2 \$MONLAP \$MON1
workspace \$ws4 output \$MON2 \$MONLAP \$MON1
workspace \$ws5 output \$MON2 \$MONLAP \$MON1

workspace \$ws6 output \$MON1 \$MONLAP \$MON2
workspace \$ws7 output \$MON1 \$MONLAP \$MON2
workspace \$ws8 output \$MON1 \$MONLAP \$MON2
workspace \$ws9 output \$MON1 \$MONLAP \$MON2
workspace \$ws10 output \$MON1 \$MONLAP \$MON2
EOF

    i3-msg reload
else
    echo "dual_home not matched: left=$MON_LEFT right=$MON_RIGHT"
fi
